"""empty message

Revision ID: 3c0c930449a9
Revises: 68f5a56b451c
Create Date: 2025-05-02 08:43:10.769600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0c930449a9'
down_revision: Union[str, None] = '68f5a56b451c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'google_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'google_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
