"""empty message

Revision ID: 59f4d89d680d
Revises: 84a035e39ab9
Create Date: 2025-05-02 08:30:57.663986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f4d89d680d'
down_revision: Union[str, None] = '84a035e39ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
