"""empty message

Revision ID: 84a035e39ab9
Revises: e1ef12cf2b88
Create Date: 2025-05-02 08:27:46.077556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a035e39ab9'
down_revision: Union[str, None] = 'e1ef12cf2b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'google_access_token')
    # ### end Alembic commands ###
