"""UserProfile: add access_topken

Revision ID: dc2a8dc71324
Revises: fe97d00dd4ae
Create Date: 2025-04-13 03:33:38.325102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2a8dc71324'
down_revision: Union[str, None] = 'fe97d00dd4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.add_column('user_profile', sa.Column('access_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'access_token')
    op.add_column('tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'user_profile', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
